// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiGvLf-MMO5uJ1fTGaQVRTL_h6Gir4PhI',
    appId: '1:56215293550:web:5753578516a1caaa88607f',
    messagingSenderId: '56215293550',
    projectId: 'sampleauth-12345',
    authDomain: 'sampleauth-12345.firebaseapp.com',
    storageBucket: 'sampleauth-12345.appspot.com',
    measurementId: 'G-02N39JGY71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5crSnCNdK_30G7VLaGnjQ1r9fvMfeMLA',
    appId: '1:56215293550:android:ee505df1f796e43088607f',
    messagingSenderId: '56215293550',
    projectId: 'sampleauth-12345',
    storageBucket: 'sampleauth-12345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0fMTm1p9Ha3Tm7vmCxMK_4zqiubUkyGw',
    appId: '1:56215293550:ios:3b92577eeb27d9ae88607f',
    messagingSenderId: '56215293550',
    projectId: 'sampleauth-12345',
    storageBucket: 'sampleauth-12345.appspot.com',
    iosClientId: '56215293550-mkau5sgc60bu8ja377s9thpg7gco91ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0fMTm1p9Ha3Tm7vmCxMK_4zqiubUkyGw',
    appId: '1:56215293550:ios:3b92577eeb27d9ae88607f',
    messagingSenderId: '56215293550',
    projectId: 'sampleauth-12345',
    storageBucket: 'sampleauth-12345.appspot.com',
    iosClientId: '56215293550-mkau5sgc60bu8ja377s9thpg7gco91ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
